# Generated by Django 4.2.16 on 2025-06-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(max_length=255)),
                ('room_number', models.IntegerField()),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('join_date', models.DateField()),
            ],
        ),
    ]
